### ISSUE TITLE
Создание  файла.

### ISSUE THREAD

**Issue by unnamemik** [unnamemik/git-seminars#1]
Создать программу на Python "Hello world".

**Comment by Kate-belozerts** [comment]
#1 work in progress

**Comment by Kate-belozerts** [comment]
#1 Done

**Comment by unnamemik** [comment]
https://us05web.zoom.us/j/81135029675?pwd=ZVE0MGdGWXVUNEduOXRxR2JHc2dPQT09

пт, 2 июн. 2023 г. в 23:08, Kate Belozertseva ***@***.***>:
